name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
        matrix:
          use_gmp: ['ON', 'OFF']
          use_arch_native: ['ON', 'OFF']
          compiler: ['g++', 'clang++']
          flags: ['-m32', '']

    steps:
    - uses: actions/checkout@v2

    - name: configure
      run: mkdir $GITHUB_WORKSPACE/build && cd $GITHUB_WORKSPACE/build && CXX=${{ matrix.compiler }} cmake -DCMAKE_CXX_FLAGS=${{ matrix.flags }} -DTERRAPHAST_BUILD_CLIB=${{ matrix.use_gmp }} -DTERRAPHAST_USE_GMP=${{ matrix.use_gmp }} -DTERRAPHAST_ARCH_NATIVE=${{ matrix.use_arch_native }} ..

    - name: build
      run: make -C $GITHUB_WORKSPACE/build -j 4

    - name: test
      run: make -C $GITHUB_WORKSPACE/build test
